### ISSUE TITLE
faça um readmed agradavel para os outros :)  

### ISSUE THREAD

**Issue by Henrytos** [D1ogooo/Portifolio___#1]
faça um bom reademed para documentar bem e depois poste no linkedin , ficou muito bonito parabens , agora só focar em projetos pessoais e adquirir experiecia

**Comment by D1ogooo** [comment]
To postando conteudo direto no meu linkedin deis de uns 2 dias

Em dom., 5 de mai. de 2024 21:18, HENRY ***@***.***> escreveu:
